### ISSUE TITLE
Gamebatte_watchOS 12 Issues

### ISSUE THREAD

**Issue by Y3H801** [gabrieloc/GIOVANNI#10] opened 2017-03-23 00:26 UTC
<img width="257" alt="screen shot 2017-03-22 at 7 24 14 pm" src="https://cloud.githubusercontent.com/assets/15676718/24226618/7148d0fc-0f35-11e7-863f-cbe3f2ff152f.png">

**Comment by gabrieloc** [comment] 2017-03-23 04:35
Duplicate of https://github.com/gabrieloc/GIOVANNI/issues/3

**Closed as completed by gabrieloc** 2017-03-23 04:35 UTC

**Comment by Y3H801** [comment] 2017-03-23 16:09
Sorry about that
