### ISSUE TITLE
Message from debugger: Terminated due to memory issue

### ISSUE THREAD

**Issue by thomasfor** [gabrieloc/GIOVANNI#8] opened 2017-03-21 19:17 UTC
When running on Apple Watch Series 0 it crashes with memory issue, works fine on the simulator.

**Comment by niccolospa** [comment] 2017-03-21 20:02
Probably is related to my issue #4

**Comment by gabrieloc** [comment] 2017-03-22 14:37
Are you on a Series 0 (2015) Apple Watch?

**Comment by niccolospa** [comment] 2017-03-22 14:44
yes

**Comment by gabrieloc** [comment] 2017-03-22 14:53
This is a duplicate of https://github.com/gabrieloc/GIOVANNI/issues/4

**Closed as completed by gabrieloc** 2017-03-22 14:53 UTC
