### ISSUE TITLE
the game only show the splash screen and then crashes - Apple Watch Series 0 (2015)

### ISSUE THREAD

**Issue by niccolospa** [gabrieloc/GIOVANNI#4] opened 2017-03-21 07:05 UTC
I got to install correctly the emulator and the game on Apple Watch but I cannot go over the splash screen. I am using a "series 0" Apple watch

**Comment by gabrieloc** [comment] 2017-03-21 09:48
Can you paste a stack trace

**Comment by niccolospa** [comment] 2017-03-21 10:35
How do I have to do?

**Comment by NickAtGit** [comment] 2017-03-21 13:48
Try restarting your iPhone & Watch

**Comment by niccolospa** [comment] 2017-03-21 14:32
I tried restarting both, but no success

**Comment by niccolospa** [comment] 2017-03-21 15:08
My Apple Watch is a 'series 0' sorry for the mistake

**Comment by jdleo** [comment] 2017-03-21 20:54
@niccolospa post the stack trace

**Comment by niccolospa** [comment] 2017-03-22 07:04
I'm trying to do it, but I'm having troubles on launching the app on Apple Watch from xCode, it stucks at first launch

**Comment by niccolospa** [comment] 2017-03-22 07:08
!(https://cloud.githubusercontent.com/assets/26550959/24186050/b0abe090-0ed6-11e7-871e-e8b8eb89665f.png)

**Comment by gabrieloc** [comment] 2017-03-22 07:09
Does the app launch in the simulator?

**Comment by niccolospa** [comment] 2017-03-22 07:11
I managed to run it on both the simulator and the apple watch, on the first one I don't know how to upload roms, on the second one, it loads for few seconds the game and then crashes, and I cannot find the stack trace after the crash, only if I pause execution

**Comment by niccolospa** [comment] 2017-03-22 07:14
This is Thread 3:
libsystem_kernel.dylib`__workq_kernreturn:
    0x211376f8 <+0>:  mov    r12, #368
    0x211376fc <+4>:  svc    #0x80
->  0x21137700 <+8>:  blo    0x21137718                ; <+32>
    0x21137704 <+12>: ldr    r12, [pc, #0x4]           ; <+24>
    0x21137708 <+16>: ldr    r12, [pc, r12]
    0x2113770c <+20>: b      0x21137714                ; <+28>
    0x21137710 <+24>: rsbne  pc, sp, #24, #18
    0x21137714 <+28>: bx     r12
    0x21137718 <+32>: bx     lr

libsystem_pthread.dylib`start_wqthread:
    0x211f51a0 <+0>:  sub    sp, sp, #8
    0x211f51a4 <+4>:  push   {r4, r5}
    0x211f51a8 <+8>:  blx    0x211f51c8                ; _pthread_wqthread
->  0x211f51ac <+12>: nop

**Comment by jdleo** [comment] 2017-03-22 08:22
@niccolospa Im going to attempt to reproduce this, one sec

**Comment by niccolospa** [comment] 2017-03-22 14:18
I tried with simulator and works fine on Apple watch "series 0"

**Comment by gabrieloc** [comment] 2017-03-22 14:37
I'm worried the Series 0 isn't powerful enough to run the app. I've been developing on the 2016 Series 1, and with new hardware and all, it's still incredibly slow. If anyone else with a Series 0 is able to run this, please let me know.

**Comment by niccolospa** [comment] 2017-03-22 14:40
when testing on xCode my Apple Watch CPU usage exceeds 90% and then crashes, as well as memory (about 3/4)

**Comment by ghost** [comment] 2017-03-23 02:39
I tested it with my Apple Watch Series 0. Can confirm that it is not powerful enough to work well. the farthest I was able to get was the loading screen for a game. Then it would crash. Sometimes I couldn't even get that far.

**Comment by thomasfor** [comment] 2017-03-23 10:44
The RAM for all watches is the same. The only difference is the processor. so it should only run slower right? I've tried 3 games, they show the first 3 screens, then it crashes with out of memory error.

**Comment by jdleo** [comment] 2017-03-23 19:27
@thomasfor the problem is that it already runs pretty slow on the newest watches; however, I'm working on a solution for the series 0. I think I might have a performance solution that will apply to every model. ill push it out

**Comment by isleep2late** [comment] 2017-03-23 22:00
This is not specific to the series 0. I am on Watch Series 2 42mm and I also can't get past the splash screen

**Comment by isleep2late** [comment] 2017-03-23 23:56
Nevermind I got it working. I had it working before but re-installed it and that's when I got problems. Make sure when you compile the program and sign it try to use the same e-mail address you used when you first used Terminal. That ended up working for me, because when I didn't use the same e-mail, I get the watch app stuck on the splash screen like some of you and it just never opens (even though it properly installed on the phone and watch)

**Comment by gabrieloc** [comment] 2017-03-24 08:36
@niccolospa Does @isleep2late 's solution work?

**Comment by niccolospa** [comment] 2017-03-24 08:43
@gabrieloc I installed properly the app, since I can load the emulator and see the games, but it stucks at game splash screen, i tried with several ROMS

**Comment by gabrieloc** [comment] 2017-03-24 08:56
Are you able to actually view a list of roms? Or does the app not get that far?

**Comment by niccolospa** [comment] 2017-03-24 09:01
I'm able to view the list of ROMs and then launch anyone, but then it freezes here ![](http://i.imgur.com/k9etvzK.jpg) or a bit later @gabrieloc

**Comment by 61Halim** [comment] 2017-03-24 13:54
I am on apple watch series 0 (2015) it crashrs after i open a game

**Comment by isleep2late** [comment] 2017-03-24 13:58
@niccolospa Okay, then that's a separate issue from the problem I've been having. My problem was that it gets stuck on the giovanni loading screen (the one with the small giovanni circle logo and the wheel spinning on the watch). But my problem only happens when the e-mail address you use in "ssh-keygen -t rsa -b 4096 -C [your_email_address]." is different from the e-mail address you use for your provisioning profile (at least that's my theory). It also happens when you just straight up download the zip, fix everything, and build it.

**Comment by niccolospa** [comment] 2017-03-24 14:02
I see, then mine should be hardware weakness. I'll wait if someone can optimize the emulator 👍🏼

**Comment by gabrieloc** [comment] 2017-03-24 14:06
Stay tuned, some people have been emailing and tweeting about optimization ideas (eg https://twitter.com/Antique_Dev/status/845085045027102720)

**Comment by niccolospa** [comment] 2017-03-24 14:09
Great! ☺️

**Comment by 61Halim** [comment] 2017-03-27 21:11
Hi gabriel are you update the optimization for apple watch series 0?

**Comment by gabrieloc** [comment] 2017-03-28 13:03
Can those of you with a series 0 test https://github.com/gabrieloc/GIOVANNI/pull/15 and see if it makes any difference? It runs _way_ faster on a 2016 series 1 now

**Comment by niccolospa** [comment] 2017-03-28 13:13
Yes, as soon as it finishes updating to 3.2 I'll test it

**Comment by niccolospa** [comment] 2017-03-28 13:54
where do I download the last version? @gabrieloc

**Comment by gabrieloc** [comment] 2017-03-28 13:58
@niccolospa https://github.com/gabrieloc/GIOVANNI/pull/15

**Comment by niccolospa** [comment] 2017-03-28 15:38
I tried but crashes at ROM's launch, but I don't know if I did it well: the first time I installed the emulator I followed Redmond Pie tutorial, then to apply #15 update, I downloaded GIOVANNI-feature-sktexture.zip from GitHub, but the folder gambatte is empty, then I copied and paste the old folder, applying the commit libgambatte/src/video.cpp manually. Is it wrong? @gabrieloc

**Comment by niccolospa** [comment] 2017-03-28 16:09
I got to install it correctly and I noticed a major improvement, the animation was quite smooth then I got this crash with this stack frame:
->  0x26002330: .long  0x746f4e65                ; unknown opcode
    0x26002334: .long  0x63696669                ; unknown opcode
    0x26002338: svcvs  #0x697461
    0x2600233c: svcvs  #0x46736e
    0x26002340: .long  0x65744972                ; unknown opcode
    0x26002344: .long  0x70003a6d                ; unknown opcode
    0x26002348: svcvs  #0x667265
    0x2600234c: svcvs  #0x4d6d72
@gabrieloc

**Comment by thomasfor** [comment] 2017-03-28 19:42
Just tried the new sktexture branch, i can actually play games now for a short wile (tetris and mario) but it crashes often.

**Comment by ghost** [comment] 2017-03-28 19:50
I can also confirm that games load and are playable on the series 0

**Comment by 61Halim** [comment] 2017-03-28 19:53
I have install on watch series 0 the latest i cant play because it crash often

**Comment by niccolospa** [comment] 2017-03-29 07:05
This is what I got this morning after launching Pokemon Yellow:
Jet`jet_context::set_fragment_texture:
    0x2807c724 <+0>:   push   {r4, r5, r6, r7, lr}
    0x2807c726 <+2>:   add    r7, sp, #0xc
    0x2807c728 <+4>:   str    r11, [sp, #-4]!
    0x2807c72c <+8>:   sub    sp, #0x8
    0x2807c72e <+10>:  mov    r4, r2
    0x2807c730 <+12>:  mov    r6, r1
    0x2807c732 <+14>:  mov    r5, r0
    0x2807c734 <+16>:  cbz    r4, 0x2807c742            ; <+30>
    0x2807c736 <+18>:  ldr    r0, [r4]
->  0x2807c738 <+20>:  ldr    r1, [r0, #0x2c]     Thread 1: EXC_BAD_ACCESS(code=1, address=0x2c)
    0x2807c73a <+22>:  mov    r0, r4
    0x2807c73c <+24>:  blx    r1
    0x2807c73e <+26>:  cmp    r0, #0x1
    0x2807c740 <+28>:  beq    0x2807c770                ; <+76>
    0x2807c742 <+30>:  ldr    r0, [r5, #0x4]
    0x2807c744 <+32>:  ldr    r1, [r0]
    0x2807c746 <+34>:  ldr    r2, [r1, #0x1c]
    0x2807c748 <+36>:  mov    r1, r6
    0x2807c74a <+38>:  blx    r2
    0x2807c74c <+40>:  mov    r2, r0
    0x2807c74e <+42>:  cmp    r2, #0x0
    0x2807c750 <+44>:  blt    0x2807c768                ; <+68>
    0x2807c752 <+46>:  ldr    r0, [r5]
    0x2807c754 <+48>:  mov    r1, r4
    0x2807c756 <+50>:  ldr.w  r3, [r0, #0x90]
    0x2807c75a <+54>:  mov    r0, r5
    0x2807c75c <+56>:  add    sp, #0x8
    0x2807c75e <+58>:  ldr    r11, [sp], #4
    0x2807c762 <+62>:  pop.w  {r4, r5, r6, r7, lr}
    0x2807c766 <+66>:  bx     r3
    0x2807c768 <+68>:  add    sp, #0x8
    0x2807c76a <+70>:  ldr    r11, [sp], #4
    0x2807c76e <+74>:  pop    {r4, r5, r6, r7, pc}
    0x2807c770 <+76>:  movw   r0, #0x2c4f
    0x2807c774 <+80>:  movw   r2, #0x202
    0x2807c778 <+84>:  movt   r0, #0x1
    0x2807c77c <+88>:  movw   r1, #0x2bdd
    0x2807c780 <+92>:  movt   r1, #0x1
    0x2807c784 <+96>:  movw   r3, #0x2c2b
    0x2807c788 <+100>: movt   r3, #0x1
    0x2807c78c <+104>: add    r0, pc
    0x2807c78e <+106>: add    r1, pc
    0x2807c790 <+108>: add    r3, pc
    0x2807c792 <+110>: blx    0x28088f2c                ; symbol stub for: jet_buffer_Metal::set_value(unsigned short)

**Comment by gabrieloc** [comment] 2017-03-29 14:44
Good to hear there's an improvement on Series 0 devices. Continuing to investigate the crash, if anyone has any ideas let me know.

**Comment by gabrieloc** [comment] 2017-03-30 15:43
SpriteKit work has been merged, constituting a [0.2 release](https://github.com/gabrieloc/GIOVANNI/releases). `jet_context::set_fragment_texture` crashes are no longer reproducible on a Series 1 device.

**Comment by niccolospa** [comment] 2017-03-30 17:48
After installing 0.2 release, after launching ROMs, screen goes white and then crashes @gabrieloc

**Comment by thomasfor** [comment] 2017-03-30 18:41
Sometimes it works fine, even after switching games. Most games are like 30+ fps too.

When I get crashes, it is in GameCoreSnapshots.swift at this line:
return Data(buffer: bufferPointer)

Error: Giovanni Game core (7): EXC_BAD_ACCESS (code=1, address=0x2a94000)

**Comment by 61Halim** [comment] 2017-03-30 19:44
Anybody test on watch series 0, crashes?

**Comment by niccolospa** [comment] 2017-03-31 13:17
@61Halim yes, sometimes it works quite well but crashes often: white screen after launching rom

**Closed as completed** 2017-04-19 15:21 UTC

**Comment by PedroSantosAzevedo** [comment] 2020-08-21 22:02
hey trying to load games on watch os 3 and getting Exc_BAD_ACCESS on createData inside GameCoreSnapshots, anyone have an idea why?
